import { useState } from "react";

const useSpeechToText = {
  'pulao': 'pulav',
  'pulav': 'pulav',
  'annamalai laddu':'Annamayya Laddu – అన్నమ్య లడ్డు',
  'annamaya laddu': 'Annamayya Laddu – అన్నమ్య లడ్డు',
  'poornam': 'Poornam – పూర్ణం',
  'poonam': 'Poornam – పూర్ణం',
  'chakara pongali': 'Chakkara Pongali – చక్కెర పంగళి',
  'apricot pudding': 'Apricot Pudding – ఆప్రికాట్ పుడ్డింగ్',
  'carrot halwa': 'Carrot Halwa – గాజరుల హల్వా',
  'bobbatlu': 'Bobbattlu',
  'bobatlu': 'Bobbattlu',
  'jalebi': 'Jilebi – జిలేబీ',
  'jilebi': 'Jilebi – జిలేబీ',
  'double ka meetha': 'Double Ka Meetha – డబుల్ కా మీథా',
  'gulab jamun': 'Gulab Jamun – గులాబ్ జామున్',
  'angur jamun': 'Angoor Jamun – అంగూర్ జామున్',
  'badam halwa': 'Badham Halwa – బాదం హల్వా',
  'badshah': 'Badhusha – బధుషా',
  'rasgulla':'rasagulla',
  'bandar laddu': 'Bandhar Laddu – బాంధర్ లడ్డు',
  'bellam jalebi': 'Bellam Jilebi – బెల్లం జిలేబీ',
  'chamcham': 'Cham Cham – చామ్ చామ్',
  'dry fruit bell': 'Dry Fruit Bhell – డ్రై ఫ్రూట్ భెల్',
  'halva':'halwa',
  'jangri': 'Jangry – జాంగ్రీ',
  'jillu': 'Jeedulu – జీడులు',
  'kaddu ka kheer': 'Kaddhu Ka Kheer – కద్దు కీ కీర్',
  'kakinada khaja': 'Kakinada Kaja – కాకినాడ కాజా',
  'puri':'poori',
  'qurbani ka meetha': 'Kurbani Ka Meetha – కుర్బాని కా మీథా',
  'malai blueberry': 'Malai Blue Berry – మలై బ్లూ బెర్రీ',
  'motichur laddu': 'Mothichoor Laddu – మొతిచూర్ లడ్డు',
  'mysore pak': 'Mysoor Pak – మైసూర్ పాక్',
  'pancharatna halwa': 'Pancha Ratan Halwa – పంచరత్న హల్వా',
  'paneer jalebi': 'Paneer Jilebi – పన్నీర్ జిలేబీ',
  'pineapple jalebi': 'Pine Apple Jilebi – అనాస జిలేబీ',
  'pineapple roll': 'Pine Apple Roll – అనాస రోల్',
  'pista katli': 'Pistha Katli – పిస్థా కట్లీ',
  'pothare kullu': 'Pootha Rekulu – పూత రేకులు',
  'pakkam gari': 'Pakam Gaare – పాకం గారే',
  'palathalikalu': 'Pala Thalikalu – పాల తలికాలు',
  'rajula poonam': 'Rajula Poornam – రాజుల పూర్ణం',
  'ragi laddu': 'Raagi Laddu – రాగి లడ్డు',
  'rasmalai': 'Rasamalai – రసమలాయ్',
  'rava kesari': 'Rawwa Kesari – రవ్వ కేశరీ',
  'sitafal rabdi': 'Seethe Phal Rabidi – సీతె ఫల రాబిడి',
  'sahi tukda': 'Shahi Thukada – షాహి తుకడా',
  'soan papdi': 'Soampapidi – సాంపాపిడి',
  'son papdi': 'Soampapidi – సాంపాపిడి',
  'som papdi': 'Soampapidi – సాంపాపిడి',
  'Om papdi': 'Soampapidi – సాంపాపిడి',
  'surya toast': 'Shubiya Toast – శుబియ టోస్ట్',
  'sunnundalu': 'Sunnu Undalu – సున్ను ఉండడాలు',
  'trifle pudding': 'Triffle Pudding – ట్రిఫిల్ పుడ్డింగ్',
  'badam cold': 'Badham Cold – బాదం కోల్డ్',
  'badam milk hot': 'Badham Milk Hot – బాదం మిల్క్ హాట్',
  'chocolate milkshake': 'Chocolate Milk Shake – చాకొలెట్ మిల్క్ షేక్',
  'litchi milkshake': 'Litchi Milk Shake – లిచీ మిల్క్ షేక్',
  'mango milkshake': 'Mango Milk Shake – మామిడి మిల్క్ షేక్',
  'muskmelon juice': 'Musk Melon Juice – మస్క్ మెలన్ జ్యూస్',
  'pineapple juice': 'Pine Apple Juice – అనాస జ్యూస్',
  'sapota milkshake': 'Sapota Milk Shake – సపోటా మిల్క్ షేక్',
  'strawberry punch': 'Straw Berry Punch – స్ట్రాబెర్రీ పంచ్',
  'strawberry milkshake': 'Strawberry Milk Shake – స్ట్రాబెర్రీ మిల్క్ షేక్',
  'sugarcane juice': 'Sugar Cane – పంచదార కంచ',
  'vanilla milkshake': 'Vanilla Milk Shake – వెనిల్లా మిల్క్ షేక్',
  'watermelon juice': 'Water Melon Juice – వాటర్ మెలన్ జ్యూస్',
  'baby corn manchurian': 'Baby corn Manchuria – బేబీ కార్న్ మంచూరియా',
  'chilli mushroom': 'Chilly mushroom – చిల్లీ మష్రూమ్',
  'chilli paneer': 'Chilly paneer – చిల్లీ పనీర్',
  'crispy corn': 'Chrispy corn – క్రిస్పీ కార్న్',
  'crispy veg': 'Chrispy veg – క్రిస్పీ వెజ్',
  'hara bhara kabab': 'Hara Bara Kabab – హరా బరా కబాబ్',
  'makai palak tikka': 'Makhai palak tikka – మక్కాయ్ పాలక్ టిక్కా',
  'pineapple tikka': 'Pine apple tikka – అనాస టిక్కా',
  'shanghai roll': 'Shangai Roll – షాంఘై రోల్',
  'jalapeno poppers': 'Jalapheno Poppers',
  'ajwain pakodi': 'Ajwan Pakodi – అజ్వాన్ పకోడి',
  'babrala vada': 'Bobbarla Wada – బొబ్బర్ల వడ',
  'babbar lavada':'Bobbarla Wada – బొబ్బర్ల వడ',
  'dahi vada': 'Dhahi Wada – దహి వడ',
  'gare': 'Gaare – గారే',
  'masala vada': 'Masala Wada – మసాలా వడ',
  'mix veg vada': 'Mix Veg Wada – మిక్స్ వెజ్ వడ',
  'nellore garage': 'Nellore Gaare – నెల్లూరు గారే',
  'onion pakode': 'Onion Pakodi – ఉల్లిపాయ పకోడి',
  'sweet corn vada': 'Sweet Corn Wada – స్వీట్ కార్న్ వడ',
  'tamalapaku bajji': 'Thamala Paku Bajji – తమల పాకు బజ్జి',
  'kerala parotta': 'Kerala Parotha – కేరళ పరోట',
  'lachha parotta': 'Laccha Parotha – లచ్చా పరోట',
  'makai ki roti': 'Makhai Ki Roti – మక్కయ్ కి రోటి',
  'methi puri': 'Methi Poori – మెథి పూరీ',
  'palak puri': 'Palak Poori – పాలక్ పూరీ',
  'pulka': 'Phulka – ఫుల్కా',
  'tawa paratha': 'Thawa Parotha – తవా పరోట'
};

export default useSpeechToText;